Story9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.user_login, name='login'),
    path('loginsuccess', views.user_loginsuccess, name='loginsuccess'),
    path('logout', views.user_logout, name='logout'),
    path('signup', views.user_signup, name='signup')
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse

def index(request):
    return render(request, 'index.html')

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")        
        if not username or not password:
            messages.error(request, "Invalid Login, Please Try Again!")
            return render(request, 'login.html')
        user = authenticate(request,username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('main:loginsuccess')
        messages.error(request,"Wrong Username or Password")
        return render(request,'login.html')
    else:   
        return render(request, 'login.html')

def user_signup(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if not username or not password:
            messages.error(request, "Please Fill out the Data Field")
            return render(request, 'signup.html')

        try:
            user = User.objects.get(username=username)
            messages.error(request, "Username is already taken by another user")
            return render(request, 'signup.html')
        except:
            user = User.objects.create_user(username=username, password=password)
            return redirect(reverse('main:index'))
    else:
        return render(request,'signup.html')

@login_required(login_url='main:index')

def user_loginsuccess(request):
    if request.method == "GET":
        return render(request, 'loginsuccess.html')

def user_logout(request):
    logout(request)
    return redirect('main:index')

main/templates/index.html
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="static/styles.css">
  </head>
  <body>
    <div class="container">
      <div class="row pt-5 mt-5 justify-content-center">
        <div class="col-md-10">
          <h1 class="text-white text-center font-weight-normal">Welcome</h1>
        </div>
      </div>
      <div class="row justify-content-center pt-5">
        <div class="col-md-2">
          <a href="{% url 'main:login' %}">
            <button type="button" class="btn  btn-grad">Login</button>
          </a>
        </div>
        <div class="col-md-2">
          <a href="{% url 'main:signup' %}">
            <button type="button" class="btn btn-grad" name="tombol_signup_landing">Sign Up</button>      
          </a>
        </div>
      </div>
    </div>
  </body>
</html>

main/templates/login.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="static/styles.css">
    </head>
    <body>
       {% for i in messages %}
        <script>alert("{{ i }}")</script>
       {% endfor %}
       <div class="container pt-5 mt-5">
           <div class="row justify-content-center">
               <div class="col-md-6">
                   <form class="text-white"action="" method="POST">
                       {% csrf_token %}
                       <label for="username">Username: </label>
                       <input type="text" name="username" id="username_box" required>
                       <br>
                       <label for="password">Password: </label>
                       <input name="password" type="password" id="password_box" required>
                       <br>
                       <input type="submit" value="Log In" class="btn btn-grad" id="login-submit">
                   </form>
               </div>
           </div>
       </div>
    </body>
</html>


    

main/templates/loginsuccess.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="static/styles.css">
    </head>
    <body>
        <div class="container mt-5">
            <h1 class="display-4 text-white ">Selamat Datang, {{ user.username }}</h1>
            <a href="{% url 'main:logout' %}"><button class="btn btn-grad">Log Out</button></a>
        </div>
    </body>
</html>

main/templates/signup.html
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="static/styles.css">
    </head>
    <body>
        {% for i in messages %}
        <script>alert("{{ i }}")</script>
        {% endfor %}
        <div class="container mt-5">
            <h1 class="text-white">Sign Up</h1>
            <br>
            <form class= "text-white" action="" method="POST">
                {% csrf_token %}
                <label for="username">Username: </label>
                <input type="text" name="username" required>
                <br>
                <label for="password">Password: </label>
                <input name="password" type="password" required>
                <br><br>
                <input type="submit" value="create" class="btn btn-grad" id="login-submit">
            </form>
        </div>
           
    </body>
</html>


   